# Generated by Django 4.1.3 on 2022-11-21 07:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('customer_name', models.TextField(max_length=100)),
                ('customer_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
