# Generated by Django 4.1.3 on 2022-11-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formdetails', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
